# Generated by Django 4.2.7 on 2024-02-17 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=255)),
                ('quantidade', models.FloatField()),
                ('cotacao', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('meta', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('acao', 'acao'), ('bdr', 'bdr'), ('fii', 'fii'), ('renda fixa', 'renda fixa')], max_length=255)),
                ('status', models.CharField(choices=[('comprar', 'comprar'), ('vender', 'vender'), ('aguardar', 'aguardar')], max_length=255)),
                ('comentarios', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ativo')},
            },
        ),
    ]
